added error/debugging messages for github() asset downloader

diff --git a/provii b/provii
--- a/provii
+++ b/provii
@@ -11,40 +11,39 @@ fi
 PROVII_BRANCH=docs-comps
 
 if command -v tput >/dev/null 2>&1; then
+	TAB="$(tput ht 2>/dev/null || echo '')"
 	if [ $(($(tput colors 2>/dev/null))) -ge 8 ]; then
 		MAGENTA="$(tput setaf 5 2>/dev/null || echo '')"
-		TAB="$(tput ht)"
+		CYAN="$(tput setaf 6 2>/dev/null || echo '')"
 		UNDERLINE="$(tput smul 2>/dev/null || echo '')"
 		NO_UNDERLINE="$(tput rmul 2>/dev/null || echo '')"
 		STYLE_RESET="$(tput sgr0 2>/dev/null || echo '')"
 	fi
 fi
 
-
 create_dir() {
 	for dir in "$@"; do
-		echo "$dir"
-		if [ ! -d "$1" ] && [ -w "$(dirname "$1")" ]; then
-				mkdir -p "$1"
-				if [ "$?" -eq 0 ]; then
-					log --created "$1"
-				else
-					warn Failed to create "$1"
-					return 1
-				fi
+		if [ ! -d "$dir" ] && [ -w "$(dirname "$dir")" ]; then
+			mkdir -p "$1"
+			if [ "$?" -eq 0 ]; then
+				log --created "$dir"
+			else
+				warn Failed to create "$dir"
+				return 1
+			fi
 		fi
 	done
 }
 
 get_installer() {
-		printf -v GITHUB_QUERY "https://api.github.com%s%s" \
-			"/repos/l0xy/provii/contents/installs/$INSTALLER" \
-			"${PROVII_BRANCH:+?ref=$PROVII_BRANCH}"
-
-		SCRIPTLET="$(curl -sSL $GITHUB_QUERY |
-			jq '.download_url' |
-			xargs curl -sSL)"
+	printf -v GITHUB_QUERY "https://api.github.com%s%s" \
+		"/repos/l0xy/provii/contents/installs/$INSTALLER" \
+		"${PROVII_BRANCH:+?ref=$PROVII_BRANCH}"
+	curl -sSL "$GITHUB_QUERY" \
+		| jq '.download_url' \
+		| xargs curl -sSL
 }
+
 ls_installers() {
 	GITHUB_QUERY_LS="$( printf \
 		"https://api.github.com/repos/l0xy/provii/contents/installs%s" \
@@ -90,23 +89,16 @@ ls_installers() {
 	done < <( curl -sSL "$GITHUB_QUERY_LS" | jq -r "$JQ_QUERY" | tr -d '"')
 }
 
-fn_install=$(
-	cat <<'EOF'
+fn_install=$( cat <<'EOF'
 BASH_FUNC_install%%=() {
 	if [ "$#" -eq 1 ]; then
 
 		mime_type=$(file -b --mime-type "$1")
 		case "$mime_type" in
 
-		text/troff)
-			case ${1##*.} in
-			1) command install "$1" "${MAN?}/man1/" ;;
-			8) command install "$1" "${MAN?}/man8/" ;;
-			*) warn "not sure where to install $1!" ;;
-			esac
-			;;
-		application/x-*)
-			command install "$1" "$BIN/"
+		*/x-*)
+			command install "$1" "$BIN/" \
+				&& log --created "$BIN/$1"
 			;;
 		*)
 			err "Could not install $1"
@@ -120,85 +112,88 @@ BASH_FUNC_install%%=() {
 EOF
 )
 
-fn___dl_github_tarball=$(
-	cat <<'EOF'
+fn___dl_github_tarball=$( cat <<'EOF'
 BASH_FUNC___dl_github_tarball%%=() {
 	REPO=$1
 	FQDN='https://github.com'
-
-	if [ $VERBOSE ]; then
-		echo Downloading archive of "$REPO"
-	fi
-	curl -#L $FQDN/$REPO/tarball/${BRANCH:-master} | tar -xzf - --strip=1
+	URL="$FQDN/$REPO/tarball/${BRANCH:-master}"
+	
+	printf '\n%s/%s\n' "$PWD" "${CYAN}${URL##*/}${STYLE_RESET}"
+	curl -#L "$URL" | tar -xzf - --strip=1
 }
 EOF
 )
 
-fn___dl_github_asset=$(
-	cat <<'EOF'
+fn___dl_github_asset=$( cat <<'EOF'
 BASH_FUNC___dl_github_asset%%=() {
-	local RE FQDN URI URL RELEASE
-	FQDN='https://api.github.com'
+	local RE FQDN URI URL RELEASE MSG
 
+	FQDN='https://api.github.com'
 	RELEASE="${3+tags/$3}"
 	RE="${2//\\/\\\\}"
 	URI="/repos/$1/releases/${RELEASE:-latest}"
 
-	if [ $VERBOSE ]; then
-		echo Querying Github for download URLs...
+	JQ_CMD='[.assets[] | { asset:.name, url:.browser_download_url }]'
+	ASSETS="$( curl -sSL "$FQDN$URI" | jq "$JQ_CMD" )"
+
+	JQ_CMD=$( printf '.[] | select( .asset | test("%s")).url' "$RE" )
+	URL=$( echo "$ASSETS" | jq -r "$JQ_CMD" )
+
+	if [ "$(echo "$URL" | wc -w)" -gt 1 ]; then
+		SUBMSG=$(printf \
+			'Regular expression %s matched more than one Github asset.' \
+			"${CYAN}${RE}${STYLE_RESET}" )
+
+		JQ_CMD=$( printf '.[] | select( .asset | test("%s")).asset' "$RE" )
+		ASSET_NAMES=$( echo "$ASSETS" | jq -r "$JQ_CMD" )
+
+		MSG="$( printf '%s Assets matched:\n\n%s\n' "$SUBMSG" "$ASSET_NAMES" )"
+		err "$MSG"
+	elif [ -z "$URL" ]; then
+		SUBMSG=$( printf 'No Github asset found for %s that matches: %s' \
+			"$1" "${CYAN}$RE${STYLE_RESET}" )
+		ASSET_NAMES="$( echo "$ASSETS" | jq -r '.[].asset_name' )"
+		MSG="$( printf '%s\nAssets found for %s:\n\n%s' \
+			"$SUBMSG" "${CYAN}$1${STYLE_RESET}" "$ASSET_NAMES" )"
+		err "$MSG"
 	fi
 
-	URL=$(curl -sSL "$FQDN$URI" | jq -r \
-		".assets[] 
-		| select( .name | test(\"$RE\"))
-		| .browser_download_url")
-
-	echo "/${URL##*/}"
+	printf '\n%s/%s\n' "$PWD" "${CYAN}${URL##*/}${STYLE_RESET}"
 	curl -#LO "$URL"
 }
 EOF
 )
 
-fn___dl_github_file__=$(
-	cat <<'EOF'
+fn___dl_github_file__=$( cat <<'EOF'
 BASH_FUNC___dl_github_file__%%=() {
 	FQDN='https://api.github.com'
 	BRANCH="${3+\?ref=$3}"
 	URI="$FQDN/repos/$1/contents/$2$3"
-
-	if [ $VERBOSE ]; then
-		echo Querying Github for download URLs...
-	fi
-
-	while read -r FILE_PATH; do
-		PATH_DEPTH=$(echo "$FILE_PATH" | tr / ' ' | wc -w)
+	
+	while read -r FILE; do
+		PATH_DEPTH=$(echo "$FILE" | tr / ' ' | wc -w)
 		if [ $PATH_DEPTH -gt 1 ]; then
-			mkdir -p $(dirname "$FILE_PATH")
+			mkdir -p $(dirname "$FILE")
 		fi
 
-		read -r DL_URL
-		# directories return 'null' for the download URL
-		# we have to recurse on them to download their contents
-		if [ "$DL_URL" == 'null' ]; then
-			__dl_github_file__ "$REPO" "$FILE_PATH"
+		read -r URL
+		# download URL shows 'null' when $FILE is a directory
+		if [ "$URL" == 'null' ]; then
+			__dl_github_file__ "$REPO" "$FILE"
 		fi
 
-		echo "/$FILE_PATH:"
-		curl -#L -o "$FILE_PATH" "$DL_URL"
+		printf '\n%s/%s\n' "$PWD" "${CYAN}${URL##*/}${STYLE_RESET}"
+		curl -#L -o "$FILE" "$URL"
 
-	done < <(curl -sSL "$URI" | jq -r '
-						if type == "object" 
-						then
-								.path,.download_url 
-						else 
-								.[] | .path,.download_url
-						end')
+	done < <( curl -sSL "$URI" | jq -r '
+		if type == "object" 
+		then .path,.download_url 
+		else .[] | .path, .download_url' )
 }
 EOF
 )
 
-fn_github=$(
-	cat <<'EOF'
+fn_github=$( cat <<'EOF'
 BASH_FUNC_github%%=() {
 	local REPO BRANCH PATH_TO_FILE ASSET_RE
 	PATH_TO_FILE=$(echo "$1" | cut -d/ -f3-)
@@ -243,15 +238,13 @@ BASH_FUNC_github%%=() {
 EOF
 )
 
-fn_log=$(
-	cat <<'EOF'
-BASH_FUNC_log%%=() {
-	echo "log:" "$@"
-}
-EOF
-)
 log() {
-	echo "log:" "$@"
+	FMT='+%Y-%m-%d %T'
+	if [ "$1" == '--created' ]; then
+		shift && printf '%s %s %s' "$(date "$FMT")" created_file "$@" >> $PROVII_LOG
+	else
+		printf '%s %s %s' "$(date "$FMT")" info "$@" >> $PROVII_LOG
+	fi
 }
 
 warn() {
@@ -263,25 +256,36 @@ err() {
 	exit 1
 }
 
-fn_warn=$(
-	cat <<'EOF'
-BASH_FUNC_warn%%=() {
-	echo "warn:" "$@"
+fn_log="$( cat <<'EOF'
+BASH_FUNC_log%%=() {
+	FMT='+%Y-%m-%d %T'
+	if [ $1 == '--created' ]; then
+		shift && echo "$(date "$FMT") created_file $@" >> $LOG
+	else
+		echo "$(date "$FMT") info $@" >> $LOG
+	fi
 }
 EOF
-)
+)"
 
-fn_err="$(
-	cat <<'EOF'
+fn_warn="$( cat <<'EOF'
+BASH_FUNC_warn%%=() {
+	echo "Warning:" "$@"
+}
+EOF
+)"
+
+fn_err="$( cat <<'EOF'
 BASH_FUNC_err%%=() {
-	echo "error:" "$@"
+	printf '\n%s: %s' "${MAGENTA}Error${STYLE_RESET}" "$@"
+	exit 1
 }
 EOF
 )"
 
 PRINT_VARIABLES="$(cat <<-'EOF'
 env \
-	| grep "^\(OS\|SCOPE\|BASH_COMP\|ZSH_COMP\|MAN\|NAME\|CFG\|CACHE\|CFG\|ARCH\|BIN\|SYSD\|LOG\)=" \
+	| grep "^\(OS\|SCOPE\|BASH_COMP\|ZSH_COMP\|MAN\|NAME\|CACHE\|CFG\|ARCH\|BIN\|SYSD\|LOG\)=" \
 	| awk -v ul="$UNDERLINE" -v mg="${MAGENTA}" -v no_style="$STYLE_RESET" '
 		BEGIN {
 			FS="="
@@ -323,42 +327,35 @@ env \
 		}'
 EOF
 )"
-run_installer() {
-	[ "$VERBOSE" ] && echo "INSTALLER: $INSTALLER"
 
-	if [ -f "${XDG_CONFIG_HOME-$HOME/.config}/proviirc" ]; then
-		. "${XDG_CONFIG_HOME-$HOME/.config}/proviirc"
-	fi
-	
-	if [ -d "${XDG_CACHE_HOME-$HOME/.cache}" ] \
-	&& [ -w "${XDG_CACHE_HOME-$HOME/.cache}" ]; then
-		PROVII_CACHE=${XDG_CACHE_HOME-$HOME/.cache}
-	else
-		PROVII_CACHE=/tmp
-	fi
+run_installer() {
+	PROVIIRC="${XDG_CONFIG_HOME-$HOME/.config}/proviirc"
+	[ -f "$PROVIIRC" ] && . "$PROVIIRC"
+
+	USER_CACHE="${XDG_CACHE_HOME-$HOME/.cache}" 
+	[ -d "$USER_CACHE" ] && [ -w "$USER_CACHE" ] \
+		&& PROVII_CACHE="$USER_CACHE/provii" \
+		|| PROVII_CACHE=/tmp/provii
+
+	[ ! "$SUMMARIZE" ] && create_dir "$PROVII_CACHE"
 	PROVII_LOG=$PROVII_CACHE/run.log
 
 	# see, https://en.wikipedia.org/wiki/Uname#Examples
-	PROVII_SYSTEM="$(uname -s | tr [:upper:] [:lower:])"
+	PROVII_SYSTEM="$( uname -s | tr [:upper:] [:lower:] )"
 	case "$(uname -m)" in
 		amd64 | x86_64 )
-			PROVII_MACHINE='(x86_64|amd64)'
-			;;
+			PROVII_MACHINE='(x86_64|amd64)' ;;
 		i386 | i586 | i686 )
-			PROVII_MACHINE='(i386|i586|i686)'
-			;;
+			PROVII_MACHINE='(i386|i586|i686)' ;;
 		*)
-			PROVII_MACHINE=unknown
-			;;
+			PROVII_MACHINE=unknown ;;
 	esac
 
 	set -a
 
-	if [ "$(id -u)" -eq "0" ]; then
-		PV_SCOPE=system
-	else
-		PV_SCOPE=user
-	fi
+	[ "$(id -u)" -eq "0" ] \
+		&& PV_SCOPE=system \
+		|| PV_SCOPE=user
 
 	if [ "$PV_SCOPE" == system ]; then
 		PV_BIN=${SYS_BIN-/usr/local/bin}
@@ -450,10 +447,9 @@ done' "$PV_BASH_COMP" >> "$PV_BASH_CONFIG"
 	create_dir $PV_{BIN,CFG,SYS}
 
 	if [ "$INSTALLER" ]; then
-		PV_TMP=$PROVII_CACHE/provii/$INSTALLER
-	
+		PV_TMP="$PROVII_CACHE/$INSTALLER"
 		if [ ! "$SUMMARIZE" ]; then
-		mkdir -pm 0700 $PV_TMP &&
+			create_dir $PV_TMP || err Failed to create temporary directory: "$PV_TMP"
 			rm -rf $PV_TMP/*
 		fi
 	fi
@@ -461,27 +457,19 @@ done' "$PV_BASH_COMP" >> "$PV_BASH_CONFIG"
 	set +a
 
 	case *:$PATH:* in
-		*:$PV_BIN:*) ;;
-
+		*:$PV_BIN:*)
+			;;
 		*)
 			[ -z $SUDO_USER ] && warn "$PV_BIN" temporarily added \
 				to PATH, manually add it to your shell configuration
 			;;
 	esac
 
-	if [ ! "$SUMMARIZE" ]; then
-		printf -v GITHUB_QUERY "https://api.github.com%s%s" \
-			"/repos/l0xy/provii/contents/installs/$INSTALLER" \
-			"${PROVII_BRANCH:+?ref=$PROVII_BRANCH}"
+	[ ! "$SUMMARIZE" ] \
+		&& SCRIPTLET="$(get_installer)" \
+		|| SCRIPTLET="$PRINT_VARIABLES"
 
-		SCRIPTLET="$(curl -sSL $GITHUB_QUERY |
-			jq '.download_url' |
-			xargs curl -sSL)"
-	else
-		SCRIPTLET="$PRINT_VARIABLES"
-	fi
-
-	/usr/bin/env -C ${PV_TMP:-$PROVII_CACHE} - \
+	/usr/bin/env -C "${PV_TMP:-$PROVII_CACHE}" - \
 		SCOPE="$PV_SCOPE" \
 		BIN="$PV_BIN" \
 		${INSTALLER:+NAME="$INSTALLER"}\
@@ -490,15 +478,17 @@ done' "$PV_BASH_COMP" >> "$PV_BASH_CONFIG"
 		${PV_MAN:+MAN="$PV_MAN"} \
 		${PV_BASH_COMP:+BASH_COMP="$PV_BASH_COMP"} \
 		${PV_ZSH_COMP:+ZSH_COMP="$PV_ZSH_COMP"} \
-		${PROVII_CACHE:+CACHE="${PV_TEMP:-$PROVII_CACHE}"} \
+		${PROVII_CACHE:+CACHE="${PV_TMP:-$PROVII_CACHE}"} \
 		${PROVII_LOG:+LOG="$PROVII_LOG"} \
 		${PROVII_MACHINE:+ARCH="$PROVII_MACHINE"} \
 		${PROVII_SYSTEM:+OS="$PROVII_SYSTEM"} \
 		${UNDERLINE:+UNDERLINE="$UNDERLINE"} \
 		${MAGENTA:+MAGENTA="$MAGENTA"} \
+		${CYAN:+CYAN="$CYAN"} \
 		${NO_UNDERLINE:+NO_UNDERLINE="$NO_UNDERLINE"} \
 		${STYLE_RESET:+STYLE_RESET="$STYLE_RESET"} \
 		${PS4:+PS4="$(tput ht)$(tput ht)$(tput setaf 6)$INSTALLER $LINENO :: $(tput sgr 0)"} \
+		${VERBOSE:+VERBOSE="$VERBOSE"} \
 		"$fn_github" \
 		"$fn___dl_github_asset" \
 		"$fn___dl_github_file__" \
@@ -507,11 +497,11 @@ done' "$PV_BASH_COMP" >> "$PV_BASH_CONFIG"
 		"$fn_log" \
 		"$fn_warn" \
 		"$fn_err" \
-		bash ${DEBUG+-x} -c "$SCRIPTLET"
+		bash ${DEBUG+-x} -e -c "$SCRIPTLET"
 }
 
-if [ "$(basename $0)" != 'provii.sh' ]; then
-	run_installer "$(basename $0)"
+if [ "$(basename "$0")" != 'provii' ]; then
+	run_installer "$(basename "$0")"
 else
 	subcommand="$1"
 	shift # remove 'install' from argument list
@@ -551,13 +541,9 @@ else
 				;;
 		esac
 		get_installer
-		echo "$SCRIPTLET"
 		;;
 	-h | --help | -help | help)
 		print_usage
-		;;
-	summary)
-		__show_summary $1
 		;;
 	esac
 fi
