added help verbage & moved the definiton of the PV_* variables into a seperate function per variable

diff --git a/provii b/provii
--- a/provii
+++ b/provii
@@ -1,6 +1,4 @@
-#!/bin/bash
-
-set -e
+#!/bin/bash -e
 
 if [ "$DEBUG" ]; then
 	set -x
@@ -33,6 +31,98 @@ create_dir() {
 			fi
 		fi
 	done
+}
+
+print_usage() {
+	if [ "$#" -eq 0 ]; then
+		echo '
+provii - command line utility installer
+Usage: 
+       provii [OPTIONS] install UTILITY
+       provii [OPTIONS] env [UTILITY]
+       provii [OPTIONS] cat UTILITY
+       provii [OPTIONS] ls
+       provii help [SUBCOMMAND]
+
+OPTIONS:
+-h, --help      print this message
+-b, --branch    choose which provii branch to work with
+-v, --verbose   prints various information depending on subcommand'
+	else
+		case "$1" in
+			install)
+				echo '
+Usage: provii install UTILITY
+
+For a list of possible utilities see:
+	provii ls
+
+To see the script that will be run by provii install run:
+	provii cat UTILITY
+
+To view the values that will be used in the variables defined in the script run:
+	provii env UTILITY'
+				;;
+			env)
+				echo '
+Usage: provii env [UTILITY]
+
+When run without any arguments provii env will show the variables 
+will populate the subshell provii runs its installers in *regardless*
+of the installer being run. These variables are derived (1) from the
+state of your system and (2) whether provii is being run with
+root privilages.
+
+Variables that will always be available in the provii environment 
+that are determined by the state of your system include the following:
+
+$OS     - operating system, determined by `uname -s`
+$LIBC   - libc variant, determined by `ldd --version`
+$ARCH   - regex associated with system architecture
+
+Variables that will vary depending on whether provii is run with root
+privilages (and thus be installed system-wide as opposed to installed
+for the current user) include the following:
+
+$BIN       - where the utilties themselves are placed 
+$MAN       - where any man pages will be installed
+$BASH_COMP - where bash completions are installed
+$ZSH_COMP  - where zsh completions are installed
+
+Additionally there are variables that are used for provii itself, i.e.
+meta-variables. The include:
+
+$LOG     - the path to  the log that keeps track of any modifications
+           made to the system
+$CACHE   - parent directory of where provii creates directories to
+           place any intermediary files created during an installation
+
+When `provii env` is run with a utilit as an argument, the following
+variables will also be shown:
+
+$NAME    - the name of the command/binary file
+$CACHE   - the subdirectory within the main $CACHE for any files 
+           generated during the installation of $NAME'
+				;;
+			cat)
+				echo '
+Usage: provii cat UTILITY
+
+Prints the entire script that is execute when `provii install UTILITY` is run'
+				;;
+			ls)
+				echo '
+Usage: provii ls
+
+Prints out all possible utilities that can be installed
+with provii along with a brief description.'
+				;;
+			*)
+				print_usage
+				;;
+		esac
+	fi
+	exit
 }
 
 get_installer() {
@@ -87,6 +177,133 @@ ls_installers() {
 						url_color, $3, url_end_style)
 				}'
 	done < <( curl -sSL "$GITHUB_QUERY_LS" | jq -r "$JQ_QUERY" | tr -d '"')
+}
+
+set_pv_bin() {
+	case "$PROVII_SCOPE" in
+		system) PV_BIN=${SYS_BIN-/usr/local/bin} ;;
+			user) PV_BIN=${USER_BIN-$HOME/.local/bin} ;;
+	esac
+	create_dir "${PV_BIN:?'Failed to set variable $BIN'}"
+}
+
+set_pv_data() {
+	case "$PROVII_SCOPE" in
+		system) PV_DATA=${SYS_DATA-/usr/local/share} ;;
+			user) PV_DATA=${USER_DATA-$HOME/.local/share} ;;
+	esac
+	create_dir "${PV_DATA:?'Failed to set variable $DATA'}"
+}
+
+set_pv_man() {
+	case "$PROVII_SCOPE" in
+		system)
+			if command -v manpath &>/dev/null; then
+				for MAN_PATH in $(manpath -g | tr : $'\n'); do
+					if [ -d "$MAN_PATH" ] && [ -w "$MAN_PATH" ]; then
+						PV_MAN="$MAN_PATH"
+						break
+					fi
+				done
+			fi
+			;;
+		user)
+			if command -v manpath &>/dev/null; then
+				PV_MAN=${USER_MAN-"$(manpath | tr : $'\n' | grep -m 1 "$HOME")"}
+			fi
+			if [ -z "$PV_MAN" ]; then
+				PV_MAN="$PV_DATA/man"
+				echo "MANDATORY_MANPATH $PV_MAN" > "$HOME/.manpath"
+			fi
+			create_dir "$PV_MAN"/man{1,8}
+			;;
+	esac
+}
+			
+set_pv_bash_comp() {
+	case "$PROVII_SCOPE" in
+		system) 
+			PV_BASH_COMP=${SYS_BASH_COMP-/etc/bash_completion.d}
+			if command -v manpath &>/dev/null; then
+				for MAN_PATH in $(manpath -g | tr : $'\n'); do
+					if [ -d "$MAN_PATH" ] && [ -w "$MAN_PATH" ]; then
+						PV_MAN="$MAN_PATH"
+						break
+					fi
+				done
+			fi
+			;;
+		user)
+			# bash-completion 2.9 introduced ${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion.d
+			if command -v rpm &>/dev/null; then
+				QUERYPKG_CMD_FMT='rpm -qa --queryformat %s  name=%s'
+			elif command -v dpkg-query &>/dev/null; then
+				QUERYPKG_CMD_FMT='dpkg-query --showformat=%s --show %s'
+			fi
+
+			if [ "$QUERYPKG_CMD_FMT" ]; then
+				BASH_COMP_VER="$($(printf "$QUERYPKG_CMD_FMT" '%{VERSION}\n' 'bash-completion' ))"
+			else
+				warn "Could not locate either rpm / dkpg-query command to determine version of bash-completion"
+			fi
+
+			if [ -n "$BASH_COMP_VER" ]; then
+				XDG_ENABLED_BASH_COMP_VER='2.9'
+				if [ "${BASH_COMP_VER//./}" -ge "${XDG_ENABLED_BASH_COMP_VER//./}" ] \
+				&& [ -n "$XDG_DATA_HOME" ] && [ -n "$XDG_CONFIG_HOME" ]; then
+					# see, https://github.com/scop/bash-completion/tree/2.8
+					PV_BASH_COMP="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion.d"
+					PV_BASH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" \
+						&& create_dir "$XDG_CONFIG_HOME"
+				else
+					# see, https://github.com/scop/bash-completion/tree/2.9
+					PV_BASH_COMP="$HOME/.bash-completion.d"
+					PV_BASH_CONFIG="$HOME/.bash_completion"
+				fi
+				create_dir "$PV_BASH_COMP"
+
+				# make sure there's a line in bash_completion (config) to
+				# source the files in bash-completion.d gets sourced
+				COMP_DIR_RE="$( printf '^[^#].*%s' "${PV_BASH_COMP//\./\\.}" )"
+				if ! grep -q "$COMP_DIR_RE" "$PV_BASH_CONFIG" 2>/dev/null; then
+					printf '
+	for i in %s/*; do
+		if [ -r "$i" ]; then
+			. "$i"
+		fi
+	done' "$PV_BASH_COMP" >> "$PV_BASH_CONFIG"
+				fi
+			fi
+	esac
+}
+
+set_pv_zsh_comp() {
+	case "$PROVII_SCOPE" in
+		system) 
+			if command -v zsh >/dev/null 2>&1; then
+				if [ -n "$fpath" ]; then
+					if ( echo "$fpath" | grep -v $HOME | grep -qi completions ); then
+						PV_ZSH_COMP="$ZSH_USER_COMP_DIR"
+					elif ( echo "$fpath" | grep -v $HOME | grep -qi custom ); then
+						PV_ZSH_COMP="$ZSH_USER_CUSTOM_DIR"
+					fi
+				fi
+			fi
+			;;
+		user) 
+			if command -v zsh >/dev/null 2>&1; then
+				if [ -n "$fpath" ]; then
+					ZSH_USER_COMP_DIR="$( printf '%s.*completions' "$HOME" )"
+					ZSH_USER_CUSTOM_DIR="$( printf '%s.*custom' "$HOME" )"
+					if ( echo "$fpath" | grep -qi "$ZSH_USER_COMP_DIR" ); then
+						PV_ZSH_COMP="$ZSH_USER_COMP_DIR"
+					elif ( echo "$fpath" | grep -qi "$ZSH_USER_CUSTOM_DIR" ); then
+						PV_ZSH_COMP="$ZSH_USER_CUSTOM_DIR"
+					fi
+				fi
+			fi
+			;;
+	esac
 }
 
 fn_install=$( cat <<'EOF'
@@ -337,6 +554,7 @@ run_installer() {
 	[ -d "$USER_CACHE" ] && [ -w "$USER_CACHE" ] \
 		&& PROVII_CACHE="$USER_CACHE/provii" \
 		|| PROVII_CACHE=/tmp/provii
+	create_dir "$PROVII_CACHE"
 
 	[ ! "$SUMMARIZE" ] && create_dir "$PROVII_CACHE"
 	PROVII_LOG=$PROVII_CACHE/run.log
@@ -357,119 +575,27 @@ run_installer() {
 			PROVII_MACHINE=unknown ;;
 	esac
 
-	set -a
-
 	[ "$(id -u)" -eq "0" ] \
-		&& PV_SCOPE=system \
-		|| PV_SCOPE=user
+		&& PROVII_SCOPE=system \
+		|| PROVII_SCOPE=user
 
-	if [ "$PV_SCOPE" == system ]; then
-		PV_BIN=${SYS_BIN-/usr/local/bin}
-		PV_DATA=${SYS_DATA-/usr/local/share}
-		PV_CFG=${SYS_CFG-/etc}
-		PV_SYSD=${SYS_SYSD-/etc/systemd/system}
-		PV_BASH_COMP=${SYS_BASH_COMP-/etc/bash_completion.d}
-		if command -v manpath &>/dev/null; then
-			for MAN_PATH in $(manpath -g | tr : $'\n'); do
-				if [ -d "$MAN_PATH" ] && [ -w "$MAN_PATH" ]; then
-					PV_MAN="$MAN_PATH"
-					break
-				fi
-			done
-		fi
-		if command -v zsh >/dev/null 2>&1; then
-			PV_ZSH_COMP=${SYS_ZSH_COMP-/usr/local/share/zsh/vendor-completions}
-		fi
+	set_pv_bin
+	set_pv_data
+	set_pv_man
+	set_pv_bash_comp
+	set_pv_zsh_comp
 
-	elif [ "$PV_SCOPE" == user ]; then
-		PV_BIN=${USER_BIN-$HOME/.local/bin}
-		PV_CFG=${USER_CFG-$HOME/.config}
-		PV_DATA=${USER_DATA-$HOME/.local/share}
-		PV_SYSD=${USER_SYSD-$HOME/.config/systemd/user.control}
-		if command -v manpath &>/dev/null; then
-			PV_MAN=${USER_MAN-"$(manpath | tr : $'\n' | grep -m 1 "$HOME")"}
-		fi
-		
-		if [ -z "$PV_MAN" ]; then
-			PV_MAN="$PV_DATA/man"
-			echo "MANDATORY_MANPATH $PV_MAN" > "$HOME/.manpath"
-		fi
-		create_dir "$PV_MAN"/man{1,8}
-
-		if command -v zsh >/dev/null 2>&1; then
-			if [ -n "$fpath" ]; then
-				ZSH_USER_COMP_DIR="$( printf '%s.*completions' "$HOME" )"
-				ZSH_USER_CUSTOM_DIR="$( printf '%s.*custom' "$HOME" )"
-				if ( echo "$fpath" | grep -qi "$ZSH_USER_COMP_DIR" ); then
-					PV_ZSHi_COMP="$ZSH_USER_COMP_DIR"
-				elif ( echo "$fpath" | grep -qi "$ZSH_USER_CUSTOM_DIR" ); then
-					PV_ZSH_COMP="$ZSH_USER_CUSTOM_DIR"
-				fi
-			fi
-		fi
-
-		# bash-completion 2.9 introduced ${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion.d
-		if command -v rpm &>/dev/null; then
-			QUERYPKG_CMD_FMT='rpm -qa --queryformat %s  name=%s'
-		elif command -v dpkg-query &>/dev/null; then
-			QUERYPKG_CMD_FMT='dpkg-query --showformat=%s --show %s'
-		fi
-
-		if [ "$QUERYPKG_CMD_FMT" ]; then
-			BASH_COMP_VER="$($(printf "$QUERYPKG_CMD_FMT" '%{VERSION}\n' 'bash-completion' ))"
-		else
-			warn "Could not locate either rpm / dkpg-query command to determine version of bash-completion"
-		fi
-
-		if [ -n "$BASH_COMP_VER" ]; then
-			XDG_ENABLED_BASH_COMP_VER='2.9'
-			if [ "${BASH_COMP_VER//./}" -ge "${XDG_ENABLED_BASH_COMP_VER//./}" ] \
-			&& [ -n "$XDG_DATA_HOME" ] && [ -n "$XDG_CONFIG_HOME" ]; then
-				# see, https://github.com/scop/bash-completion/tree/2.8
-				PV_BASH_COMP="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion.d"
-				PV_BASH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" \
-					&& create_dir "$XDG_CONFIG_HOME"
-			else
-				# see, https://github.com/scop/bash-completion/tree/2.9
-				PV_BASH_COMP="$HOME/.bash-completion.d"
-				PV_BASH_CONFIG="$HOME/.bash_completion"
-			fi
-			create_dir "$PV_BASH_COMP"
-
-			# make sure there's a line in bash_completion (config) to
-			# source the files in bash-completion.d gets sourced
-			COMP_DIR_RE="$( printf '^[^#].*%s' "${PV_BASH_COMP//\./\\.}" )"
-			if ! grep -q "$COMP_DIR_RE" "$PV_BASH_CONFIG" 2>/dev/null; then
-				printf '
-for i in %s/*; do
-	if [ -r "$i" ]; then
-		. "$i"
-	fi
-done' "$PV_BASH_COMP" >> "$PV_BASH_CONFIG"
-			fi
-		fi
-
-  else
-    err 'scope of the installation could not be determined..'
-  fi
-	
 	if [ ! "$SUMMARIZE" ]; then
 		# format this to look nice and tabbed out with awks printf
 		echo "${MAGENTA}binary:${STYLE_RESET} $INSTALLER"
 		echo "${MAGENTA}destination:${STYLE_RESET} $PV_BIN"
 	fi
 
-	create_dir $PV_{BIN,CFG,SYS}
-
 	if [ "$INSTALLER" ]; then
 		PV_TMP="$PROVII_CACHE/$INSTALLER"
-		if [ ! "$SUMMARIZE" ]; then
-			create_dir $PV_TMP || err Failed to create temporary directory: "$PV_TMP"
-			rm -rf $PV_TMP/*
-		fi
+		create_dir "$PV_TMP" || exit 1
+		rm -rf "$PV_TMP"/*
 	fi
-
-	set +a
 
 	case *:$PATH:* in
 		*:$PV_BIN:*)
@@ -485,11 +611,9 @@ done' "$PV_BASH_COMP" >> "$PV_BASH_CONFIG"
 		|| SCRIPTLET="$PRINT_VARIABLES"
 
 	/usr/bin/env -C "${PV_TMP:-$PROVII_CACHE}" - \
-		SCOPE="$PV_SCOPE" \
-		BIN="$PV_BIN" \
 		${INSTALLER:+NAME="$INSTALLER"}\
-		${PV_CFG:+CFG="$PV_CFG"} \
-		${PV_SYSD:+SYSD="$PV_SYSD"} \
+		SCOPE="$PROVII_SCOPE" \
+		BIN="$PV_BIN" \
 		${PV_MAN:+MAN="$PV_MAN"} \
 		${PV_BASH_COMP:+BASH_COMP="$PV_BASH_COMP"} \
 		${PV_ZSH_COMP:+ZSH_COMP="$PV_ZSH_COMP"} \
@@ -499,9 +623,9 @@ done' "$PV_BASH_COMP" >> "$PV_BASH_CONFIG"
 		${PROVII_MACHINE:+ARCH="$PROVII_MACHINE"} \
 		${PROVII_SYSTEM:+OS="$PROVII_SYSTEM"} \
 		${UNDERLINE:+UNDERLINE="$UNDERLINE"} \
+		${NO_UNDERLINE:+NO_UNDERLINE="$NO_UNDERLINE"} \
 		${MAGENTA:+MAGENTA="$MAGENTA"} \
 		${CYAN:+CYAN="$CYAN"} \
-		${NO_UNDERLINE:+NO_UNDERLINE="$NO_UNDERLINE"} \
 		${STYLE_RESET:+STYLE_RESET="$STYLE_RESET"} \
 		${PS4:+PS4="$(tput ht)$(tput ht)$(tput setaf 6)$INSTALLER $LINENO :: $(tput sgr 0)"} \
 		${VERBOSE:+VERBOSE="$VERBOSE"} \
@@ -519,22 +643,30 @@ done' "$PV_BASH_COMP" >> "$PV_BASH_CONFIG"
 if [ "$(basename "$0")" != 'provii' ]; then
 	run_installer "$(basename "$0")"
 else
-	subcommand="$1"
-	shift # remove 'install' from argument list
+	subcommand="$1" && shift
 	case "$subcommand" in
 	install)
-		for inst in $*; do
-			INSTALLER="$inst" run_installer
+		case "$1" in
+			-h | --help | help ) print_usage 'install' ;;
+		esac
+		for APP in $*; do
+			INSTALLER="$APP" run_installer
 		done
 		;;
 	ls)
+		case "$1" in
+			-h | --help | help ) print_usage 'ls' ;;
+		esac
 		ls_installers
 		;;
 	env)
+		case "$1" in
+			-h | --help | help ) print_usage 'env' ;;
+		esac
 		SUMMARIZE=1
 		if [ $# -gt 0 ]; then
-			for inst in $*; do
-				INSTALLER="$inst" run_installer
+			for APP in $*; do
+				INSTALLER="$APP" run_installer
 			done
 		else
 			run_installer
@@ -542,7 +674,11 @@ else
 		;;
 	cat)
 		case "$1" in
+			-h | --help | help )
+				print_usage 'cat'
+				;;
 			-b | --branch )
+				shift
 				[ -n "$1" ] \
 					&& PROVII_BRANCH="$1" \
 					|| print_usage 'cat'
@@ -558,8 +694,8 @@ else
 		esac
 		get_installer
 		;;
-	-h | --help | -help | help)
-		print_usage
+	-h | --help | help )
+		print_usage "$1"
 		;;
 	esac
 fi
