revision to last ocmmit

diff --git a/provii b/provii
--- a/provii
+++ b/provii
@@ -35,14 +35,12 @@ if command -v tput >/dev/null 2>&1; then
 	if [ $(($(tput colors 2>/dev/null))) -ge 8 ]; then
 		RED="$(tput setaf 3 2>/dev/null || echo '')"
 		MAGENTA="$(tput setaf 5 2>/dev/null || echo '')"
-		YELLOW="$(tput setaf 4 2>/dev/null || echo '')"
 		CYAN="$(tput setaf 6 2>/dev/null || echo '')"
 		UNDERLINE="$(tput smul 2>/dev/null || echo '')"
 		NO_UNDERLINE="$(tput rmul 2>/dev/null || echo '')"
 		STYLE_RESET="$(tput sgr0 2>/dev/null || echo '')"
 	fi
-	STYLE_ERROR="$RED"
-	STYLE_WARNING="$MAGENTA"
+	STYLE_ERROR="$MAGENTA"
 	STYLE_ECHO="$MAGENTA"
 	STYLE_VAR="$MAGENTA"
 	STYLE_FILES="$CYAN"
@@ -101,10 +99,9 @@ create_dir() {
 
 style() {
 	case "${1:?}" in
-	ERROR) STYLE="$RED" ;;
-	WARNING) STYLE="$MAGENTA" ;;
+	ERROR) STYLE="$MAGENTA" ;;
 	COLOR) STYLE="$MAGENTA" ;;
-	VAR) STYLE="$CYAN" ;;
+	VAR) STYLE="$MAGENTA" ;;
 	FILE) STYLE="$CYAN" ;;
 	DIR) STYLE="$CYAN" ;;
 	HEADER) STYLE="${UNDERLINE}${CYAN}" ;;
@@ -125,7 +122,6 @@ prompt() {
 install_jq() {
 	JQ_VERSION="1.6"
 	JQ_URL="https://github.com/stedolan/jq/releases/download/jq-$JQ_VERSION"
-	JQ_TARGET_DIR="$HOME/.local/bin"
 
 	set_provii_os
 	set_provii_arch
@@ -145,6 +141,7 @@ install_jq() {
 
 	[ -d "$JQ_TARGET_DIR" ] || create_dir "$JQ_TARGET_DIR"
 	curl -sSLo "$JQ_TARGET_DIR/jq" "$JQ_URL/$JQ_FILE"
+	chmod ug+rx "$JQ_TARGET_DIR/jq"
 
 	JQ="$(command -v jq || "$JQ_TARGET_DIR/jq")"
 
@@ -165,7 +162,7 @@ source_proviirc() {
 
 		if [ "$VERBOSE" ]; then
 			_PROVIIRC_VARS_RE=$(printf '^provii_%s=\\b' "$PROVII_VARS")
-			printf '\t%s\n' "$(grep "$_PROVIIRC_VARS_RE" "$PROVIIRC")"
+			printf '%s%s\n' "$TAB" "$(grep "$_PROVIIRC_VARS_RE" "$PROVIIRC")"
 		fi
 
 		. "$PROVIIRC"
@@ -259,57 +256,32 @@ set_provii_data() {
 	esac
 	create_dir "${PROVII_DATA:?'Failed to set variable $DATA'}"
 }
+
 has_package() {
-	if [ "$#" -eq 2 ] && [ "$1" = '-v' ] && [ -n "$2" ]; then
-		ECHO_PKG_VERSION=1
+	if [ "$#" -eq 2 ] && [ "$1" = '--version' ] && [ -n "$2" ]; then
+		ECHO_PACKAGE_VERSION=1
 		PACKAGE="$2"
 	elif [ "$#" -eq 1 ] && [ -n "$1" ]; then
 		PACKAGE="$1"
 	else
-		err "Usage: has_package [-v] PACKAGE"
+		err "Usage: has_package [--version] PACKAGE"
 	fi
 
 	if has_cmd rpm; then
-		QUERYPKG_CMD_FMT='rpm -qa --queryformat %{VERSION}\\n  name=%s'
+		QUERYPKG_CMD_FMT='rpm -qa --queryformat %s  name=%s'
 	elif has_cmd dpkg-query; then
-		QUERYPKG_CMD_FMT='dpkg-query --showformat=${Version}\\n --show %s'
+		QUERYPKG_CMD_FMT='dpkg-query --showformat=%s --show %s'
 	else
 		err "Function has_package failed to locate " \
 			"either (1) rpm or (2) dpkg-query commands."
 	fi
 
-	PACKAGE_VERSION="$(`printf "$QUERYPKG_CMD_FMT"  $PACKAGE` \
-      | sed -En 's/([[:digit:]]:)?(.*)(-.*)/\2/p')"
-
-    case "$ECHO_PKG_VERSION" in
-      ''|0) return 1 ;;
-      *) echo "$PACKAGE_VERSION"
-    esac
+	PACKAGE_VERSION="$($(printf "$QUERYPKG_CMD_FMT" '%{VERSION}\n' "$PACKAGE"))"
+	if [ -n "$PACKAGE_VERSION" ]; then
+		[ "$ECHO_PACKAGE_VERSION" ] && echo "$PACKAGE_VERSION"
+		return 0
+	fi
 }
-
-# has_package() {
-# 
-#     echo packagakeeege "$PKG"
-# 	if has_cmd rpm; then
-#       PKG_QUERY_CMD='rpm -qa --queryformat %q  name=%s'
-#       PKG_QUERY_FMT='%{VERSION}\n'
-#     elif has_cmd dpkg-query; then
-#       PKG_QUERY_CMD="dpkg-query -W -f '%s' %s "
-#       #PKG_QUERY_CMD="dpkg-query -W -f '%s' %s | sed -En 's/([[:digit:]]:)?(.*)(-.*)/\\2/p'"
-#       PKG_QUERY_FMT='${Version}\\n'
-#     else
-#       err Function has_package failed to locate \
-#         either \(1\) rpm or \(2\) dpkg-query commands.
-#     fi
-# 
-# 	PACKAGE_VERSION=`printf "$PKG_QUERY_CMD" "$PKG_QUERY_FMT" "$PKG"`
-#     echo "PACKAGE_VERSION $PACKAGE_VERSION"
-# 
-#     case "$ECHO_PKG_VER" in
-#       ''|0) return 1 ;;
-#       *) echo "$PACKAGE_VERSION"
-#     esac
-# }
 
 rm_app() {
 	set_provii_log
@@ -419,7 +391,7 @@ set_provii_bash_comp() {
 	system)
 		PROVII_BASH_COMP=${SYS_BASH_COMP-/etc/bash_completion.d}
 		if has_cmd manpath; then
-			for MAN_PATH in $(manpath -g | tr : "$CHAR_NL"); do
+			for MAN_PATH in $(manpath -g | tr : $'\n'); do
 				if [ -d "$MAN_PATH" ] && [ -w "$MAN_PATH" ]; then
 					PROVII_MAN="$MAN_PATH"
 					break
@@ -430,7 +402,7 @@ set_provii_bash_comp() {
 	user)
 		# bash-completion 2.9 introduced the follow as a directory for completions:
 		# ${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion.d
-		BASH_COMP_VER="$(has_package -v 'bash-completion')"
+		BASH_COMP_VER="$(has_package --version 'bash-completion')"
 
 		if [ -n "$BASH_COMP_VER" ]; then
 			XDG_ENABLED_BASH_COMP_VER='2.9'
@@ -464,17 +436,82 @@ done' "$PROVII_BASH_COMP" >>"$PROVII_BASH_CONFIG"
 	esac
 }
 
+# set_provii_zsh_comp() {
+# 	if has_cmd zsh; then
+# 		case "${PROVII_SCOPE:?}" in
+# 		system)
+# 			ZSH_COMP_DEFAULT=/usr/local/share/zsh/site-functions
+# 			ZSH_COMP_FALLBACK=/usr/share/zsh/site-functions
+# 
+# 			SYSTEM_WIDE_FPATH="$(zsh -c '. /etc/zshrc &>/dev/null; echo "$fpath"')"
+# 			if [ -n "$SYSTEM_WIDE_FPATH" ]; then
+# 				if [ -d "$ZSH_COMP_DEFAULT" ]; then
+# 					ZSH_COMP_DIR="$ZSH_COMP_DEFAULT"
+# 				elif [ -d "$ZSH_COMP_FALLBACK" ]; then
+# 					ZSH_COMP_DIR="$ZSH_COMP_DEFAULT"
+# 				fi
+# 			fi
+# 			;;
+# 		user)
+# 			ZSH_COMP_DEFAULT="$(
+# 				zsh -c '
+# 				if [ -f /etc/zshrc ]; then
+# 					. /etc/zshrc &>/dev/null
+# 				fi
+# 				if [ -f "$HOME/.zshrc" ]; then
+# 					. "$HOME/.zshrc" &>/dev/null
+# 				fi
+# 
+# 				if [ -n "$ZSH" ] && [ -d "$ZSH/completions" ]; then
+# 					if [ -d "$ZSH/completions" ]; then
+# 						RE="$(
+# 							printf "(?:^|[[:space:]])%s(?:\$|[[:space:]])" \
+# 								"$ZSH/completions"
+# 						)"
+# 						if echo "$fpath" | grep -Eq "$RE"; then
+# 							echo $ZSH/completions && exit
+# 						fi
+# 					elif [ -n "$ZSH_CUSTOM" ] && [ -d "$ZSH_CUSTOM" ]; then
+# 						echo $ZSH_CUSTOM && exit
+# 					else
+# 						RE="$(
+# 							printf "(?:^|[[:space:]])%s[^ ]+/%s(?:\$|[[:space:]])" \
+# 								"$HOME" "completions"
+# 						)"
+# 						if echo "$fpath" | grep -Eq "$RE"; then
+# 							echo "$fpath" | grep -Eo "$RE" && exit
+# 						fi
+# 
+# 						FALLBACK="$(
+# 							echo "$fpath" \
+# 								| grep -Eo "$(printf "(?:^| )%s[^ ]+(?:\$| )" "$HOME")" \
+# 								| tail -1
+# 						)"
+# 						[ -z "$FALLBACK" ] && exit 1
+# 
+# 						echo "$FALLBACK"
+# 					fi
+# 				fi'
+# 			)"
+# 			if [ -n "$ZSH_COMP_DEFAULT" ]; then
+# 				PROVII_ZSH_COMP="$ZSH_COMP_DEFAULT"
+# 			fi
+# 			;;
+# 		esac
+# 	fi
+# }
+
 set_provii_zsh_comp() {
 	if has_cmd zsh; then
 
 		case "${PROVII_SCOPE:?}" in
 		system)
 			ZSH_DIR="$(zsh -c '
-                . /etc/zsh/zshrc &>/dev/null
+                . /etc/zshrc &>/dev/null
                 echo $ZSH'
             )"
 			SYSTEM_FPATH="$( export CHAR_NL CHAR_SPCE; zsh -c '
-                . /etc/zsh/zshrc &>/dev/null
+                . /etc/zshrc &>/dev/null
                 echo "$fpath" | tr $CHAR_SPCE $CHAR_NL'
             )"
 
@@ -501,31 +538,30 @@ set_provii_zsh_comp() {
 
 		user)
 			USER_FPATH="$(export CHAR_NL CHAR_SPCE; zsh -c '
-              . /etc/zsh/zshrc &>/dev/null
+              . /etc/zshrc &>/dev/null
               . ${ZDOTDIR:-$HOME}/.zshrc &>/dev/null
-              echo "$fpath" | tr $CHAR_SPCE $CHAR_NL | grep -m1 ^$HOME'
+              echo "$fpath" | tr $CHAR_SPCE $CHAR_NL'
             )"
 			ZDOTDIR="$( zsh -c '
-              . /etc/zsh/zshrc &>/dev/null
+              . /etc/zshrc &>/dev/null
               . ${ZDOTDIR:-$HOME}/.zshrc &>/dev/null
               echo ${ZDOTDIR:-$HOME}'
             )"
 
             # leave without setting PROVII_ZSH_COMP if no dirs
             # in fpath located in user's home directory
-			if [ -z "$USER_FPATH" ]; then
-              return 0
+			if echo "$USER_FPATH" | grep -m1 '^$HOME'; then
+                USER_FPATH="$(echo "$USER_FPATH" | grep -m1 '^$HOME')"
+                ZDOTDIR_COMPS="$(printf '%s/completions' "$ZDOTDIR")"
+                ZDOTDIR_CUSTOM="$(printf '%s/custom' "$ZDOTDIR")"
+                ZSH_COMP_DEFAULT="$(echo "$USER_FPATH" | grep -m1 "^$HOME")"
+
+                case "$USER_FPATH" in
+                  *$ZDOTDIR_COMPS*) PROVII_ZSH_COMP="$ZDOTDIR_COMPS" ;;
+                  *$ZDOTDIR_CUSTOM*) PROVII_ZSH_COMP="$ZDOTDIR_CUSTOM" ;;
+                  *) PROVII_ZSH_COMP="$ZSH_COMP_DEFAULT" ;;
+                esac
             fi
-
-            ZDOTDIR_COMPS="$(printf '%s/completions' "$ZDOTDIR")"
-            ZDOTDIR_CUSTOM="$(printf '%s/custom' "$ZDOTDIR")"
-            ZSH_COMP_DEFAULT="$(echo "$USER_FPATH" | grep -m1 "^$HOME")"
-
-            case "$SYSTEM_FPATH" in
-              *$ZDOTDIR_COMPS*) PROVII_ZSH_COMP="$ZDOTDIR_COMPS" ;;
-              *$ZDOTDIR_CUSTOM*) PROVII_ZSH_COMP="$ZDOTDIR_CUSTOM" ;;
-              *) PROVII_ZSH_COMP="$ZSH_COMP_DEFAULT" ;;
-            esac
 			;;
 		esac
 
@@ -535,7 +571,12 @@ set_provii_zsh_comp() {
 
 set_provii_libc() {
 	if command -v ldd >/dev/null 2>&1; then
-		case "$(ldd --version 2>&1 | head -1 | tr "[:upper:]" "[:lower:]")" in
+		LDD_OUTPUT="$(
+			ldd --version 2>/dev/null \
+				| head -1 \
+				| tr "[:upper:]" "[:lower:]"
+		)"
+		case "$LDD_OUTPUT" in
 		*musl*) PROVII_LIBC=musl ;;
 		*gnu* | *glibc*) PROVII_LIBC=gnu ;;
 		*) err "failed to determine libc version, exiting." ;;
@@ -545,24 +586,21 @@ set_provii_libc() {
 	fi
 }
 
-# see, https://en.wikipedia.org/wiki/Uname#Examples
 set_provii_os() {
-    [ -z "$PROVII_OS" ] && {
-      PROVII_OS="$(uname -s | tr "[A-Z]" "[a-z]")"
-    }
+	# see, https://en.wikipedia.org/wiki/Uname#Examples
+	PROVII_OS="${PROVII_OS:-"$(uname -s | tr "[:upper:]" "[:lower:]")"}"
 }
 
 set_provii_arch() {
-    [ -z "$PROVII_ARCH" ] && {
-      PROVII_ARCH="$(uname -m | tr "[A-Z]" "[a-z]")"
-    }
+	PROVII_ARCH="${PROVII_ARCH:-"$(uname -m | tr "[:upper:]" "[:lower:]")"}"
 }
 
 set_provii_scope() {
-    case "$(id -u)" in
-      0) PROVII_SCOPE=system ;;
-      *) PROVII_SCOPE=user ;;
-    esac
+	if [ "$(id -u)" -eq "0" ]; then
+		PROVII_SCOPE=system
+	else
+		PROVII_SCOPE=user
+	fi
 }
 
 get_installer() {
@@ -659,7 +697,7 @@ ls_installers() {
 		"${PROVII_BRANCH:+?ref=$PROVII_BRANCH}")"
 	JQ_QUERY='.[] | [ .name, .download_url ] | @csv'
 
-	for line in $(curl -sSL "$GITHUB_QUERY_LS" | jq -r "$JQ_QUERY" | tr -d \"); do
+	for line in $(curl -sSL "$GITHUB_QUERY_LS" | jq -r "$JQ_QUERY" | tr -d '"'); do
 		(
 			APP="${line%,*}"
 			curl -sSL "${line#*,}" |
@@ -930,26 +968,15 @@ log() {
 	true
 }
 
-_WARNING_PREFIX='Warning: '
-_WARNING_PREFIX_SPACER="$(printf '%*s' "$(printf %s "$_WARNING_PREFIX" | wc -c)" ' ')"
 warn() {
-  if [ "$1" = '-p' ]; then
-    shift; PRESS_ENTER_TO_CONTINUE=1
-  fi
-
-  printf "\n%s%s" "$_WARNING_PREFIX" "$*" | fmt -w "${_TABLE_WIDTH:-100}" | sed "s/$_WARNING_PREFIX/$(style WARNING "$_WARNING_PREFIX")/"
-
-  if [ "$PRESS_ENTER_TO_CONTINUE" ]; then
-    unset PRESS_ENTER_TO_CONTINUE
-    read RESPONSE
-  fi
+	echo "warn:" "$@"
 }
 
 _ERROR_PREFIX='Error: '
 _ERROR_SPACER="$(printf '%*s' "$(printf %s "$_ERROR_PREFIX" | wc -c)" ' ')"
 export _ERROR_PREFIX _ERROR_SPACER
 err() {
-	printf "\n%s%s" "$(style ERROR "$_ERROR_PREFIX")" "$*" | fmt -w 80
+	printf "\n%s%s" "${STYLE_ERROR}$_ERROR_PREFIX${STYLE_RESET}" "$*" | fmt -w 80
 	exit 1
 }
 
@@ -970,8 +997,7 @@ EOF
 fn_warn="$(
 	cat <<'EOF'
 BASH_FUNC_warn%%=() {
-  printf "\n%s%s" "$(style WARNING $_WARNING_PREFIX)" "$*" | fmt -w 80
-  read RESPONSE
+echo "Warning:" "$@"
 }
 EOF
 )"
@@ -979,7 +1005,7 @@ EOF
 fn_err="$(
 	cat <<'EOF'
 BASH_FUNC_err%%=() {
-	printf "\n%s%s" "$(style ERROR $_ERROR_PREFIX)" "$*" | fmt -w 80
+	printf "\n%s%s" "${STYLE_ERROR}$_ERROR_PREFIX${STYLE_RESET}" "$*" | fmt -w 80
 exit 1
 }
 EOF
@@ -1056,11 +1082,6 @@ gather_facts() {
 }
 
 run_installer() {
-    if ! has_cmd strace; then
-      warn command strace not found. provii will not be able to create log \
-        of files created during installations. Install strace to enable logging.
-    fi
-    
 	/usr/bin/env -C "$PROVII_CACHE${INSTALLER:+/$INSTALLER}" - \
 		${INSTALLER:+NAME="$INSTALLER"} \
 		SCOPE="$PROVII_SCOPE" \
@@ -1099,7 +1120,7 @@ run_installer() {
 	STRACE_RE='^.*(([[:digit:]]{2}:?){3}).*[[:digit:]]<(.*)>'
 	DATE="$(date --iso-8601)"
 	TEMP_LOG="$(mktemp -p "$PROVII_CACHE")"
-    
+
 	strace -p "$PID" -fytze trace=open,creat,openat 2>&1 |
 		grep -E 'O_CREAT|O_TRUNC' |
 		grep -v 'O_APPEND' |
@@ -1123,7 +1144,6 @@ run_installer() {
 		}' \
 		"$TEMP_LOG" "$PROVII_LOG" >"$PROVII_LOG.new"
 	mv "$PROVII_LOG.new" "$PROVII_LOG"
-    cat $TEMP_LOG
 }
 
 if has_cmd jq; then
