edited ./provii to run properly on alpine (increased protability) + added some new install scripts

diff --git a/installs/fd b/installs/fd
--- a/installs/fd
+++ b/installs/fd
@@ -1,21 +1,13 @@
 github sharkdp/fd fd-.*x86_64.*unknown-linux-musl\.tar\.gz$
-tar -xf * && cd fd*
+tar -xf * && cd fd*/
 
 install fd
 
-if [ -w $PREFIX/share/man/man1/ ]
-&& [ ! -f $PREFIX/share/man/man1/fd.1 ]
-    install fd.1 $PREFIX/share/man/man1/
-else
-    warn "fd installed but failed to install man page" 
-fi
+install fd.1 $PREFIX/share/man/man1/ \
+	|| warn "fd installed but failed to install man page" 
+install autocompletion/fd.bash-completion $CFG/bash-completion.d/ \
+	|| warn "fd installed but failed to install bash completions" 
 
-if [ -w $CFG/bash-completion.d ] \
-&& [ ! -f $CFG/bash-completion.d/fd.bash-completion ]
-then
-    install autocompletion/fd.bash-completion \
-	$CFG/bash-completion.d/
-else
-    warn "fd installed but failed to install bash completions" 
-fi
-
+#TO-DO:
+#cp complete/rg.bash $BASH_COMPLETION/
+#cp doc/rg.1 $MAN/man1/
